### ISSUE TITLE
It is recommended to export footerClassName or remove default footer's css

### ISSUE THREAD

**Issue by cisen** [react-component/table#267]
https://github.com/react-component/table/blob/61b15904587b048575ecbad8a615fddb6153bc1e/src/Table.js#L459
The default css
```css
.ant-table-footer {
    padding: 21px 16px;
    background: #fafafa;
    border-radius: 0 0 4px 4px;
    position: relative;
    border-top: 1px solid #dae1ea;
}
```
If I want to change the footer's style and don't want to change the global style, the default style is a bit hard to change. I think we shouldn't have a default style wrapper div. The `footer` api is enough.
