### ISSUE TITLE
固定列头高度 BUG，以及 column 的 width 属性 BUG！

### ISSUE THREAD

**Issue by shangdev** [react-component/table#366]
1. 如图所示：

![image](https://user-images.githubusercontent.com/15621520/63337829-3e476600-c374-11e9-8bfc-f12c912773b2.png)

这是复现demo：https://codesandbox.io/embed/jolly-waterfall-2jqcv

2. width列只作用于固定列，内容区columns设置了width不起作用，无论内容是中文还是英文。

**Comment by shangdev** [comment]
demo：https://codesandbox.io/s/angry-tereshkova-84vcb?fontsize=14

上面出现的问题：固定列头高度偏高；width属性只对固定列起作用。

版本：6.7.0

**Comment by ineo6** [comment]
是浏览器默认样式导致的问题，`rc-table`获取的高度会多了`4px`，如果要解决，我们需要重置` border-spacing`为0，或者在项目引入`normalize.css`

```css
table {
    border-collapse: separate;
    border-spacing: 2px;
}
```
